"""Enrichment: Contact Sample sourcing, classification, and Connection Note generation."""

from .connection_note import (
    FIT_LINE,
    RECRUITER_CTA,
    RUSSIAN_SPEAKER_CTA,
    complete_outreach_fallback_template,
    generate_connection_note_template,
    generate_complete_outreach_template,
    generate_outreach_templates,
    minimal_fallback_template,
)
from .classifier import classify_contacts, normalize_apify_employee, _normalize_apify_employee
from .contact_sample import (
    ApifyTimeoutError,
    CONTACT_SAMPLE_SIZE,
    RECRUITER_FUNCTION_IDS,
    RECRUITER_SAMPLE_SIZE,
    _fetch_apify_employees_at_url,
    _run_apify_actor,
    _run_apify_for_company_page,
    _run_apify_for_recruiters,
    _run_apify_for_slug,
    company_cache_slug,
    company_slug_candidates,
    linkedin_company_slug_from_url,
    normalize_company_slug,
    normalize_linkedin_company_url,
    normalize_linkedin_url,
    poster_to_apify_item,
)
from .source import source_contacts
from .coordinator import begin_enrichment, abort_enrichment, clear_enrichment_prior

__all__ = [
    "FIT_LINE",
    "RECRUITER_CTA",
    "RUSSIAN_SPEAKER_CTA",
    "ApifyTimeoutError",
    "CONTACT_SAMPLE_SIZE",
    "RECRUITER_FUNCTION_IDS",
    "RECRUITER_SAMPLE_SIZE",
    "abort_enrichment",
    "begin_enrichment",
    "classify_contacts",
    "clear_enrichment_prior",
    "company_cache_slug",
    "company_slug_candidates",
    "complete_outreach_fallback_template",
    "generate_connection_note_template",
    "generate_complete_outreach_template",
    "generate_outreach_templates",
    "linkedin_company_slug_from_url",
    "minimal_fallback_template",
    "normalize_apify_employee",
    "normalize_company_slug",
    "normalize_linkedin_company_url",
    "normalize_linkedin_url",
    "poster_to_apify_item",
    "source_contacts",
    "_fetch_apify_employees_at_url",
    "_normalize_apify_employee",
    "_run_apify_actor",
    "_run_apify_for_company_page",
    "_run_apify_for_recruiters",
    "_run_apify_for_slug",
]
