"""Backward-compatible facade for Enrichment modules."""

from .enrichment import (
    CONTACT_SAMPLE_SIZE,
    FIT_LINE,
    RECRUITER_CTA,
    RUSSIAN_SPEAKER_CTA,
    ApifyTimeoutError,
    _fetch_apify_employees_at_url,
    _normalize_apify_employee,
    _run_apify_actor,
    _run_apify_for_company_page,
    _run_apify_for_slug,
    classify_contacts,
    company_cache_slug,
    company_slug_candidates,
    generate_connection_note_template,
    generate_outreach_templates,
    linkedin_company_slug_from_url,
    minimal_fallback_template,
    normalize_company_slug,
    normalize_linkedin_company_url,
    normalize_linkedin_url,
    source_contacts,
)

__all__ = [
    "ApifyTimeoutError",
    "CONTACT_SAMPLE_SIZE",
    "FIT_LINE",
    "RECRUITER_CTA",
    "RUSSIAN_SPEAKER_CTA",
    "classify_contacts",
    "company_cache_slug",
    "company_slug_candidates",
    "generate_connection_note_template",
    "generate_outreach_templates",
    "linkedin_company_slug_from_url",
    "minimal_fallback_template",
    "normalize_company_slug",
    "normalize_linkedin_company_url",
    "normalize_linkedin_url",
    "source_contacts",
    "_fetch_apify_employees_at_url",
    "_normalize_apify_employee",
    "_run_apify_actor",
    "_run_apify_for_company_page",
    "_run_apify_for_slug",
]
